main: svar.ajneb97.ServerVariables
version: ${project.version}
name: ServerVariables
api-version: 1.13
softdepend: [PlaceholderAPI]
folia-supported: true

commands:
  servervariables:
    description: Main command of ServerVariables
    aliases: [svar]