main: svar.ajneb97.ServerVariables
version: 2.0.2
name: ServerVariables
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  servervariables:
    description: Main command of ServerVariables
    aliases: [svar]